@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

actor Student

participant ":Ui" as UI
participant "controller:ModulePlannerController" as A #white

participant "currentUserCommand:UserCommand" as UC
participant "student:Student" as S #white
participant "modulesMajor:ModuleList" as M #white
participant "modulesTaken:ModuleList" as T #white
participant "modulesLeft:ModuleList" as L #white


'A -> A: handleUserInputTillExitCommand

'Student -> UI:

A -> UI: getUserCommand()
UI -> Student: getUserCommand()
Student --> UI: "left"
UI --> A: userInput "left"

A -> UC **: create
activate UC
UC --> A: currentUserCommand "left"

A -> UC: processCommand()

UC -> S: getModuleCodesLeft()






A -> S: getModulesMajor()

S --> A: Return modulesMajor:ModuleList


A -> S: getModulesTaken()

S --> A: Return modulesTaken:ModuleList


A -> M: modulesMajor.showModulesDiff(modulesTaken)


M -> T: getMainModuleList()

T --> M: Return Modules Taken




M -> L **: ModuleList()
L --> M: Return Modules Left


A <-- M: Display Modules Left


Student <-- A: Display Modules Left

UC --> A

UI --> Student
@enduml