@startuml
'https://plantuml.com/sequence-diagram

'autonumber
'autoactivate on

actor Student

participant ":Ui" as UI
participant "<<class>> \n:Module\nInfoView" as MIV


Student -> UI: getUser\nCommand() \n"left"
activate UI
note bottom
This command
returns the
modules left
to the user
end note

participant "controller:\nMain\nController" as MC #white

UI -> MC: handleUser\nInputTillExit\nCommand()
activate MC

participant "currentUser\nCommand:\nUserCommand" as UC #white

participant "<<class>> \n:ModuleMethods\nController" as MMC


MC -> UC **: create
activate UC
UC --> MC: currentUser\nCommand "left"
deactivate UC

MC -> UC: processCommand()
activate UC

box "Model" #LightBlue
participant "student:\nStudent" as S #white
participant "moduleCodesLeft:\nArrayList<String>" as MCL #white
participant "schedule:\nSchedule" as SCH #white
participant "modules\nPlanned:\nModuleList" as MP #white
participant "completed\nModuleCodes:\nArrayList<String>" as CMC #white
end box


UC -> S: getModuleCodesLeft()
activate S


'create moduleCodesLeft
S -> MCL **: create
activate MCL
MCL --> S
deactivate MCL


'schedule.getModulesPlanned().getCompletedModuleCodes()
S -> SCH: getModulesPlanned()
activate SCH
SCH --> S: modulesPlanned:ModuleList
deactivate SCH


S -> MP: modulesPlanned.getCompletedModuleCodes()
activate MP
MP --> S: completedModuleCodes:ArrayList<String>
deactivate MP


loop moduleCode

    S -> CMC: completedModuleCodes.contains(moduleCode)
    activate CMC
    CMC --> S: contains:Boolean
    deactivate CMC

    opt !contains
        'moduleCodesLeft.add(moduleCode)
        S -> MCL: moduleCodesLeft\n.add(moduleCode)
        activate MCL
        MCL --> S
        deactivate MCL
    end

end

destroy MCL

S --> UC: moduleCodesLeft\n:ArrayList<String>
deactivate S

UC -> MMC: showModulesLeft\n(moduleCodesLeft)

MMC -> UI: displayMessage()
UI --> Student
UI --> MMC


MMC -> MIV: printModuleStringArray(moduleCodesLeft)
activate MIV
MIV --> Student
MIV --> MMC
deactivate MIV


MMC --> UC

UC --> MC
destroy UC


MC --> UI
deactivate MC
UI --> Student
deactivate UI



@enduml