@startuml
'https://plantuml.com/sequence-diagram
'legend top left
'  <color blue> Blue activation </color> denote public method calls
'  <color red> Red activation</color> denote private method calls
'endlegend

autonumber
autoactivate on


actor Student

participant "controller:ModulePlannerController" as A #white
participant "student:Student" as S #white
participant "ModuleServiceController" as MSC #white


Student -> A: Execute 'Required' Command

A -> S: getMajor()
'activate S
S --> A: Return major
'deactivate S

A -> MSC: getRequiredModules(major)
'activate MSC
MSC -> MSC: printRequiredModules(major)
MSC --> MSC: Display Required Modules

MSC --> A: Display Required Modules
'deactivate MSC

Student <-- A: Display Modules Left
@enduml